openai:
  organization: "org-2TXEkGhl0FgvXtEqD5jVe4t8"
  project_id: "proj_7gUKR9cm7IQPCH3q2XVEBZAT"
  secret_id: "sk-kPxoCemhtK6vMY1tkbaDb6TqTKx7f8lxuF-MVdaRBOT3BlbkFJ8HZg05rla8ZP2nYG1soPWW-MA3PvfqxgBofmAKSsAA"